name: CI/CD Pipeline For Football Team App

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run player service tests via Makefile
        working-directory: ./Player_service
        run: make test

      - name: Run buy player service tests via Makefile
        working-directory: ./Buy_player_serivce
        run: make test

      - name: Run sell player service tests via Makefile
        working-directory: ./Sell_player_service
        run: make test
